.TH SWAPPER 1
.SH NAME
swapper \- Swap tiles to remove them
.SH SYNOPSIS
.TP 5
\fBswapper\fR [\fIOPTION\fR]
.RI 
.br

.SH OPTIONS
.PP
.br
\fB-s --no-sound\fR          Disables sound;
                       more efficient than setting volume(s) to 0.
.br
.br
\fB-f --fullscreen\fR        Start in fullscreen.
.br
.br
\fB-t --testing\fR           Enable testing of custom games and themes.
.br
.br
\fB-v --version\fR           Prints version.
.br
.br
\fB-h --help\fR              Prints this message.

.SH DESCRIPTION
.PP
Remove tiles by color, by number, by letter.

.PP
Features:
.br
 - many variants
.br
 - multiple players collaborating or competing
.br
 
.SH AUTHOR
.PP
Written by Stefano Marsili <efanomars@gmx.ch>.

.SH LICENSE
.PP
Copyright © 2019-2020 Stefano Marsili.

.PP
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
